Load Dataset

In [1]:
import numpy as np

In [5]:
data = np.genfromtxt('dataset/processed.cleveland.data', delimiter=',', dtype=str)
data[data == '?'] = np.nan
data = data.astype(float)

[[63.  1.  1. ...  0.  6.  0.]
 [67.  1.  4. ...  3.  3.  2.]
 [67.  1.  4. ...  2.  7.  1.]
 ...
 [57.  1.  4. ...  1.  7.  3.]
 [57.  0.  2. ...  1.  3.  1.]
 [38.  1.  3. ... nan  3.  0.]]


Remove rows with missing values

In [6]:
rows_without_nan = ~np.isnan(data).any(axis=1)

cleaned_data = data[rows_without_nan]

print(cleaned_data)

[[63.  1.  1. ...  0.  6.  0.]
 [67.  1.  4. ...  3.  3.  2.]
 [67.  1.  4. ...  2.  7.  1.]
 ...
 [68.  1.  4. ...  2.  7.  2.]
 [57.  1.  4. ...  1.  7.  3.]
 [57.  0.  2. ...  1.  3.  1.]]


Standard Normalize

In [7]:
mean = np.mean(cleaned_data)
std_dev = np.std(cleaned_data)
z_score = (cleaned_data - mean) / std_dev

[[ 0.26545699 -0.54444343 -0.54444343 ... -0.55750634 -0.47912888
  -0.55750634]
 [ 0.31770863 -0.54444343 -0.5052547  ... -0.51831761 -0.51831761
  -0.53138052]
 [ 0.31770863 -0.54444343 -0.5052547  ... -0.53138052 -0.46606597
  -0.54444343]
 ...
 [ 0.33077154 -0.54444343 -0.5052547  ... -0.53138052 -0.46606597
  -0.53138052]
 [ 0.18707953 -0.54444343 -0.5052547  ... -0.54444343 -0.46606597
  -0.51831761]
 [ 0.18707953 -0.55750634 -0.53138052 ... -0.54444343 -0.51831761
  -0.54444343]]


PCA

In [ ]:
from sklearn.decomposition import PCA

pca = PCA(n_components=12)
principle_components =  pca.fit_transform(cleaned_data)

explained_variance = pca.explained_variance_ratio_
print("Explained Variance: ", explained_variance)
cumulative_explained_variance = np.cumsum(explained_variance)
